In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv(r"C:\Users\nagap\Downloads\diabetes (1).csv")

In [4]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [6]:
df[df.isnull()].count()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
df.shape

(768, 9)

In [8]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [9]:
df["Outcome"].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [10]:
df.groupby("Outcome").mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

In [11]:
df.corr()["Outcome"].sort_values()

BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
DiabetesPedigreeFunction    0.173844
Pregnancies                 0.221898
Age                         0.238356
BMI                         0.292695
Glucose                     0.466581
Outcome                     1.000000
Name: Outcome, dtype: float64

In [12]:
X = df.drop("Outcome",axis=1)
y = df["Outcome"]

In [13]:
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [14]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=7)

In [16]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
X_train

array([[ 2.21124332, -0.25635346,  0.80035334, ...,  1.85869458,
         1.38157439,  1.06697501],
       [-0.53604176,  0.05182162,  0.0681732 , ...,  0.87654509,
         1.26457779, -0.84406847],
       [ 0.07446603, -0.62616354, -0.03642397, ...,  0.07296823,
        -0.95835763,  0.02458766],
       ...,
       [-1.14654956, -1.92049886, -0.45481262, ..., -1.34285767,
         0.81159095,  2.97801849],
       [-0.84129566, -0.4412585 , -0.55940978, ..., -1.01122277,
        -0.83236129, -1.01779969],
       [ 1.29548163,  1.83923705,  0.17277036, ...,  0.06021304,
         0.76359234,  0.2851845 ]])

In [18]:
X_test

array([[-0.84129566, -0.90352111, -0.35021546, ..., -0.64132231,
         0.34660446, -0.75720285],
       [ 0.99022773,  1.90087206,  0.80035334, ...,  0.46837906,
         0.36460393,  1.58816869],
       [ 2.82175112,  1.00716435,  1.11414484, ..., -0.69234307,
         0.7995913 ,  0.89324379],
       ...,
       [-1.14654956,  1.31533942,  0.38196469, ...,  2.67502663,
         0.88358886, -0.67033724],
       [-0.23078786, -1.11924366, -0.55940978, ...,  0.26429605,
        -0.38537428, -0.67033724],
       [ 0.68497383, -0.07144841,  1.42793633, ..., -0.44999449,
        -0.92235868, -0.23600918]])

In [19]:
model = svm.SVC(kernel="linear")

In [20]:
model.fit(X_train,y_train)

SVC(kernel='linear')

In [21]:
score_train = model.predict(X_train)
accuracy_score(y_train,score_train)

0.7858472998137802

In [22]:
score_test = model.predict(X_test)
accuracy_score(y_test,score_test)

0.7835497835497836

In [23]:
def predicting():
    input_data = (4,110,92,0,0,37.6,0.191,30)
    input_aray = np.asarray(input_data)
    input_aray = input_aray.reshape(1,-1)
    input_aray = sc.transform(input_aray)
    print(input_aray)
    predic = model.predict(input_aray)
    
    if(predic[0]==0):
        print("The person is Non diabetic")
    else:
        print("The person is Diabetic")

In [24]:
predicting()

[[ 0.07446603 -0.28717096  1.218742   -1.27277614 -0.6983268   0.68521726
  -0.82036164 -0.23600918]]
The person is Non diabetic


C:\Users\nagap\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [31]:
import pickle

In [32]:
filename = "diabetes_model.sav"

In [35]:
pickle.dump(model,open(filename,'wb'))

array([[-0.84129566, -0.90352111, -0.35021546, ..., -0.64132231,
         0.34660446, -0.75720285],
       [ 0.99022773,  1.90087206,  0.80035334, ...,  0.46837906,
         0.36460393,  1.58816869],
       [ 2.82175112,  1.00716435,  1.11414484, ..., -0.69234307,
         0.7995913 ,  0.89324379],
       ...,
       [-1.14654956,  1.31533942,  0.38196469, ...,  2.67502663,
         0.88358886, -0.67033724],
       [-0.23078786, -1.11924366, -0.55940978, ...,  0.26429605,
        -0.38537428, -0.67033724],
       [ 0.68497383, -0.07144841,  1.42793633, ..., -0.44999449,
        -0.92235868, -0.23600918]])